# codemagic.yaml
workflows:
  build:  # <- Теперь ID = "build" (проще некуда)
    name: Build iOS PWA - Simulator
    working_directory: src
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          pod install --repo-update
      
      - name: Build for Simulator
        script: |
          xcodebuild build \
            -workspace "GrafChat.xcworkspace" \
            -scheme "GrafChat" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16e' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
